server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cat_v5?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver