server:
  port: 2001
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.64.133:22122
image:
  server: http://192.168.64.133/